repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: git://github.com/doublify/pre-commit-clang-format
    rev: 62302476d0da01515660132d76902359bed0f782
    hooks:
    -   id: clang-format

repos:
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.1.1
    hooks:
    -   id: clang-tidy
        args:
        - -checks=clang-diagnostic-return-type
