name: cpplint

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: true

      - name: Install deps
        run: python3 -m pip install cpplint

      - name: Update compile database
        run: |
          make clean
          intercept-build make

      - name: run cpplint
        run: cpplint --filter=-build/include_subdir,-readability/nolint,-whitespace/line_length src/*.c
