name: Memory leak check

on: push

jobs:
  heapcheck-solve:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: true

      - name: Install gproftools
        run: |
          sudo apt-get install -y google-perftools libgoogle-perftools-dev
          sudo ln -s /usr/lib/x86_64-linux-gnu/libtcmalloc.so /usr/lib/libtcmalloc.so

      - name: Build
        run: make gperftools
        env:
          CFLAGS: -DGRID_SIZE=2 -DN_GRIDS=2

      - name: Detect Leaks on single solution
        run: ./dancing-links --single-solution --quiet < samples/5x8_2xAll_freePieces.dat
        env:
          HEAPCHECK: normal

      - name: Detect Leaks on multiple solutions
        run: ./dancing-links --multiple-solutions --quiet < samples/5x5_5_pentoI.dat
        env:
          HEAPCHECK: normal

      - name: Detect Leaks on generate coverset from file
        run: ./dancing-links --sudoku-gen samples/sudoku/sudoku_2.in
        env:
          HEAPCHECK: normal

      - name: Detect Leaks on generate coverset from str
        run: ./dancing-links --sudoku-gen 0100002030000004
        env:
          HEAPCHECK: normal
