name: Run Solver on sample problems

on: push

jobs:
  run-benchmarks:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: true

      - name: Build (2x2)
        run: make rebuild
        env:
          CFLAGS: -DGRID_SIZE=2 -DN_GRIDS=2

      - name: Run simple problem, default args
        run: ./dancing-links --multiple-solutions < samples/5x5_5_pentoI.dat

      - name: Run simple problem with, find all solutions
        run: ./dancing-links --multiple-solutions < samples/5x5_5_pentoI.dat

      - name: Run complex problem, single solution
        run: ./dancing-links --single-solution < samples/5x8_2xAll_freePieces.dat

      - name: Run sudoku gen and solve
        run: |
          ./dancing-links --sudoku-gen samples/sudoku/sudoku_2.in > sudoku_test.dat
          ./dancing-links --single-solution < sudoku_test.dat
          ./dancing-links --sudoku-parse output.dat

      - name: Build (3x3)
        run: make rebuild
        env:
          CFLAGS: -DGRID_SIZE=3 -DN_GRIDS=3

      - name: Run sudoku gen and solve
        run: |
          ./dancing-links --sudoku-gen samples/sudoku/sudoku.in > sudoku_test.dat
          ./dancing-links --single-solution < sudoku_test.dat
          ./dancing-links --sudoku-parse output.dat
