name: Run Solver on sample problems

on: push

jobs:
  run-benchmarks:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: true

      - name: Build
        run: make

      - name: Run simple problem, default args
        run: ./dlx --multiple-solutions < samples/5x5_5_pentoI.dat

      - name: Run simple problem with, find all solutions
        run: ./dlx --multiple-solutions < samples/5x5_5_pentoI.dat

      - name: Run complex problem, single solution
        run: ./dlx --single-solution < samples/5x8_2xAll_freePieces.dat
